export const DIETARY_OPTIONS = [
  "vegetarian",
  "vegan",
  "pescatarian",
  "flexitarian",
  "keto",
  "paleo",
  "mediterranean",
  "dash",
  "gluten-free",
  "dairy-free",
  "nut-free",
  "soy-free",
  "diabetic-friendly",
  "heart-healthy",
  "high-protein",
  "low-calorie",
  "pregnancy-friendly",
  "baby-toddler",
  "baby-food",
  "quick-easy",
  "meal-prep-friendly",
  "budget-friendly",
]

export const CUISINE_OPTIONS = [
  "italian",
  "mexican",
  "asian",
  "indian",
  "thai",
  "american",
  "french",
  "japanese",
  "middle-eastern",
]
